[package]
name = "whitelist-hide-controller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
whitelist-hide-core = { path = "../core" }
whitelist-hide-runtime = { path = "../runtime" }
whitelist-hide-macos = { path = "../platform-macos" }
whitelist-hide-linux = { path = "../platform-linux" }
whitelist-hide-windows = { path = "../platform-windows" }

[lints]
workspace = true
