[package]
name = "whitelist-hide-desktop"
version = "0.1.0"
description = "Desktop application for whitelist-hide"
edition = "2024"

[lib]
name = "whitelist_hide_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
whitelist-hide-core = { path = "../../../crates/core" }
whitelist-hide-service = { path = "../../../crates/service" }
whitelist-hide-macos = { path = "../../../crates/platform-macos" }
whitelist-hide-windows = { path = "../../../crates/platform-windows" }
whitelist-hide-linux = { path = "../../../crates/platform-linux" }

[workspace]
